### ISSUE TITLE
novice installation S2geometry on Windows issues

### ISSUE THREAD

**Issue by Platolita** [google/s2geometry#374]
Starting working on S2lib since this week, but I'm newbie to such code like S2/H3, and a junior undergraduate.
Below are my questions:

1. From S2geometry.io/about/install, I was told windows is not supported for running the S2 code now. That doesn't mean I couldn't use S2 to develop something in my windows 11 x64, right? Then I have to learn to use CMake or Linux to avoid this problem?

2. Besides, I'm learning S2 for related project, where I bulid a coding system and realize the function of Rider-Hailing matching & assignment. But the lack of project experience and computer expertise like OS and compilation principles, I don't get the what role that S2/H3 lib would play, and don't know how a Rider-Hailing system is bulit with S2lib and front-end&rear-end, Is there any exanples?

May guys never die:)

**Comment by smcallis** [comment]
We don't support windows explicitly as part of our releases, mostly due to the fact we do all our development on Linux.  I know people have gotten it to compile on windows but I imagine it might be a pain.  

I'm not sure what a Rider-Hailing system is but it sounds like you'd probably want to match up user locations with driver locations to match drivers with riders, which S2 could be used to do, but you'd have to define your requirements more precisely.

**Comment by jmr** [comment]
You can try with vcpkg. https://vcpkg.link/ports/s2geometry

**Comment by Platolita** [comment]
Thank you, guys.
