### ISSUE TITLE
advantage and disadavantage of s2 

### ISSUE THREAD

**Issue by wyfSunflower** [google/s2geometry#51]
Who can tell me:
1.What's the advantage and disadavntage of s2? What scenes could s2 to be used?
2.Compare to R-Tree, what's the advantage and disadvantage of s2?
Thanks!

**Comment by jmr** [comment]
1. See the ["notable features" section of the blog post](https://opensource.googleblog.com/2017/12/announcing-s2-library-geometry-on-sphere.html) and the [overview doc](http://s2geometry.io/about/overview).

2. It's hard to say unless you have a particular library using R-trees in mind to compare it to.

What are you trying to do?

**Comment by jmr** [comment]
> I need spatial index implement for back end and front end map navigation. 

It can do that.

> Why does it not use regular hexagon to projection? 

I'm not sure what you mean, since the first step is to project onto the cube. There's no Platonic solid with hexagons as faces.  Even then,  I don't see how you would subdivide the hexagon to get child hexagons.

@ericveach could give you the full explanation.

> I think it can generate less distortion than square. 

There's also simplicity and speed. The sphere -> cube projection being used isn't the one with minimum distortion. See [s2coords.h](https://github.com/google/s2geometry/blob/master/src/s2/s2coords.h#L228).

> I still do not understand the relation of orientation , origin orientation face, i , j ,cellid and position of hilbert curve. I have n point of (latitude, longtitude), 

Take a look at the comments in [s2coords.h](https://github.com/google/s2geometry/blob/20c8f339cc9a55fdca1c0e8ab519da399752e70b/src/s2/s2coords.h#L30).  You don't need to understand everything in order to use the library, though.

> I want to construct a polygon and judge point is inside it or not,but when I convert it into S2Loop, it throw out error that some edges are crossed. I don't know how to do. 

Open another issue with your code and the error and I'll take a look.

> What's the best interface to cover specified region using specified level of cellID?

`S2RegionCoverer` with `set_fixed_level` as an `Option`.  You probably don't want to do that, as the covering could be very large.

Look at `S2RegionTermIndexer` and the `term_index.cc` example.

> What about Boost.Geometry.Index for R-Tree? 

I don't know it, but I don't think it handles spherical geometry.

**Comment by wyfSunflower** [comment]
Thanks for your patient replay.
