### ISSUE TITLE
Possible bounding box miscalculation

### ISSUE THREAD

**Issue by a1983** [google/s2geometry#82]
I slightly modified `RectBounder::MaxLatitudeRandom` unit test from s2latlng_rect_bounder_test.cc :
```c++
TEST(RectBounder, MaxLatitudeFixed)
{
    S2Point l = S2LatLng::FromDegrees(1, 1).ToPoint();
    S2Point h = S2LatLng::FromDegrees(1, 0).ToPoint();

    S2LatLngRect cd_bound = GetEdgeBound(l, h);
    auto test = GetEdgeBound(l, h).lat().hi();

    auto ctrl = S2LatLng::Latitude(h).radians();

    EXPECT_NEAR(ctrl, test, kRectError.lat().radians());
}
```
and got test failure:
```
The difference between ctrl and test is 6.6445824213265392e-07, which exceeds kRectError.lat().radians(), where
ctrl evaluates to 0.017453292519943295,
test evaluates to 0.017453956978185428, and
kRectError.lat().radians() evaluates to 2.2204460492503131e-15.
```
Is it approximation error miscalculation, or something wrong with my test?

**Comment by jmr** [comment]
This is expected behavior. Note that S2 uses geodesic (great circle) edges.
http://s2geometry.io/about/overview

The shortest path between (1, 0) and (1, 1) goes above latitude=1. This is easier to see with higher latitudes and longer distances:
http://www.gcmap.com/mapui?P=45,-45-45,45

The geodesic is on a plane going through the center of the sphere. The latitude=1 plane does not go through the center.

If you change your test to
```
    auto ctrl = S2LatLng::Latitude(S2::Interpolate(0.5, l, h)).radians();
```
it will pass.

**Comment by jmr** [comment]
Also, if you want the answer your original test had, just use
```
S2LatLngRect rect(l, h);
```
or (if you have more points to add)
```
S2LatLngRect rect;
rect.AddPoint(l);
rect.AddPoint(h);
rect.AddPoint(...);
```

**Comment by a1983** [comment]
Thanks a million. I got it now. And thanks for the great library!
