### ISSUE TITLE
Polygon Intersection

### ISSUE THREAD

**Issue by DinosL** [google/s2geometry#89]
Hello,

I am trying to run the following simple example to see how polygon intersection works, but I cannot understand the result.

```
 vector<S2Point> a_vertices = {
    S2LatLng::FromDegrees(-72.2832416,42.9280532).Normalized().ToPoint(),
    S2LatLng::FromDegrees(-72.2832891,42.9254167).Normalized().ToPoint(),
    S2LatLng::FromDegrees(-72.2797593,42.9254285).Normalized().ToPoint(),
    S2LatLng::FromDegrees(-72.2795911,42.9280336).Normalized().ToPoint()
  };

  vector<S2Point> b_vertices = {
    S2LatLng::FromDegrees(-78.8190079,24.4099126).Normalized().ToPoint(),
    S2LatLng::FromDegrees(-78.5223770,23.7479149).Normalized().ToPoint(),
    S2LatLng::FromDegrees(-76.7316055,23.7981855).Normalized().ToPoint(),
    S2LatLng::FromDegrees(-72.2795911,42.9280336).Normalized().ToPoint()
     };

  S2Polygon a(make_unique<S2Loop>(a_vertices));
  S2Polygon b(make_unique<S2Loop>(b_vertices));
  cout << a.Intersects(&b) << "\n";
```

Given these two polygons, the output is 1, meaning the two polygons are intersecting. But, in reality that is not true. Maybe I don't get something that is written in the documentation, but at the moment I cannot find what.

Any help would be appreciated.

**Comment by jmr** [comment]
The first thing to note is that [polygons are defined so that the interior is on the left side](https://github.com/google/s2geometry/blob/master/src/s2/s2polygon.h#L55).  You have two very large polygons that enclose most of the sphere except for a small hole.  You can check this with [`S2Polygon::GetArea`](https://github.com/google/s2geometry/blob/master/src/s2/s2polygon.h#L256) and see if it's closer to 0 or 4π.

Even when you invert them, your polygons intersect. You can use [`S2Polygon::InitToIntersection`](https://github.com/google/s2geometry/blob/master/src/s2/s2polygon.h#L370) and [`s2textformat::ToString`](https://github.com/google/s2geometry/blob/master/src/s2/s2text_format.h#L274) to help see what's going on.

Also note that the last vertex of both polygons is the same.  This looks like the most north-east vertex in both cases. A non-empty intersection is expected.

**Comment by DinosL** [comment]
> The first thing to note is that polygons are defined so that the interior is on the left side.

If I understand this correctly, that means that if I want to define a polygon I should start the s2points from the bottom right/ top right corner and continue counter-clockwise? I noticed that if I change the order of the points the outcome of the Intersects method changes.

I now have this example and it still says that they intersect. I checked the area and the polygons are not too big. 

```
vector<S2Point> a_vertices = {
        S2LatLng::FromDegrees(-90,20).Normalized().ToPoint(),
        S2LatLng::FromDegrees(-90,25).Normalized().ToPoint(),
        S2LatLng::FromDegrees(-85,25).Normalized().ToPoint(),
        S2LatLng::FromDegrees(-85,20).Normalized().ToPoint()
};
    
vector<S2Point> b_vertices = {
       S2LatLng::FromDegrees(-45,20).Normalized().ToPoint(),
       S2LatLng::FromDegrees(-45,25).Normalized().ToPoint(),
       S2LatLng::FromDegrees(-47,25).Normalized().ToPoint(),
       S2LatLng::FromDegrees(-47,20).Normalized().ToPoint()
};
S2Polygon a(make_unique<S2Loop>(a_vertices));
S2Polygon b(make_unique<S2Loop>(b_vertices));
cout << a.Intersects(&b) << "\n";

```

What am I missing?

**Comment by DinosL** [comment]
Is the counter-clockwise condition mandatory for points also or is it only for polygons? What I am trying to achieve is to use the TestContainment method provided [here](https://s2geometry.io/devguide/s2shapeindex). I noticed that only if the points are given in a counter-clockwise format the outcome is correct. Why is that? I understand why this can be happening in polygons but I don't get why that is the case for point containment also. If I understand the pip problem correctly, orientation does not matter when checking whether a point is inside a polygon. I am correct? Is there a way to eliminate the orientation problem?

**Comment by jmr** [comment]
A point is just a point. The order of the points in the `const vector<S2Point>& points` argument won't matter. They're processed individually and not put in a loop or polygon.

Can you show your code, the output you're getting, and the output you expect to get?
